### ISSUE TITLE
💡 [Feature] 카테고리, 룰 공통 코드 적용

### ISSUE THREAD

**Issue by cofls980** [project-mijeong/spring-boot-back-end#104]
## 💡 기능 개요

- 카테고리와 룰을 공통 코드로 적용

## 📝 기능 상세 내용

- 카테고리와 룰을 공통 코드로 서비스에 적용

## ✅ TODO

- [x] 공통 코드 테이블 생성
- [x] 카테고리와 룰 데이터 삽입
- [x] 기존 방 테이블에 카테고리와 룰 컬럼 추가
- [x] 서비스에 적용
