### ISSUE TITLE
💡 [Feature] 어드민 페이지 공통 코드 CRUD 기능 구현

### ISSUE THREAD

**Issue by cofls980** [project-mijeong/spring-boot-back-end#183]
## 💡 기능 개요

- 어드민 페이지 공통 코드 CRUD 기능 구현

## 📝 기능 상세 내용

- 어드민 페이지 공통 코드 CRUD 기능 구현

## ✅ TODO

- [x] 어드민 페이지 공통 코드 조회 기능 구현
- [x] 어드민 페이지 공통 코드 생성 기능 구현
- [x] 어드민 페이지 공통 코드 수정 기능 구현
- [ ] 어드민 페이지 공통 코드 CRUD 기능 구현
